summary = {
   "Afghanistan": 4,
   "Albania": 2,
   "Algeria": 3,
   "American Samoa": 8,
   "Andorra": 2,
   "Angola": 3,
   "Anguilla": 8,
   "Antarctica (the territory South of 60 deg S)": 5,
   "Antigua and Barbuda": 8,
   "Argentina": 2,
   "Armenia": 7,
   "Aruba": 7,
   "Australia": 4,
   "Austria": 2,
   "Azerbaijan": 4,
   "Bahamas": 3,
   "Bahrain": 2,
   "Bangladesh": 9,
   "Barbados": 3,
   "Belarus": 2,
   "Belgium": 4,
   "Belize": 4,
   "Benin": 2,
   "Bermuda": 1,
   "Bhutan": 4,
   "Bolivia": 6,
   "Bosnia and Herzegovina": 2,
   "Botswana": 1,
   "Bouvet Island (Bouvetoya)": 4,
   "Brazil": 4,
   "British Indian Ocean Territory (Chagos Archipelago)": 2,
   "British Virgin Islands": 5,
   "Brunei Darussalam": 4,
   "Bulgaria": 3,
   "Burkina Faso": 7,
   "Burundi": 5,
   "Cambodia": 5,
   "Cameroon": 2,
   "Canada": 2,
   "Cape Verde": 7,
   "Cayman Islands": 7,
   "Central African Republic": 6,
   "Chad": 6,
   "Chile": 5,
   "China": 9,
   "Christmas Island": 5,
   "Cocos (Keeling) Islands": 2,
   "Colombia": 4,
   "Comoros": 7,
   "Congo": 4,
   "Cook Islands": 4,
   "Costa Rica": 2,
   "Cote d'Ivoire": 4,
   "Cuba": 3,
   "Cyprus": 1,
   "Czech Republic": 4,
   "Denmark": 2,
   "Djibouti": 5,
   "Dominica": 5,
   "Dominican Republic": 4,
   "Ecuador": 6,
   "Egypt": 4,
   "El Salvador": 3,
   "Equatorial Guinea": 6,
   "Eritrea": 5,
   "Estonia": 3,
   "Ethiopia": 4,
   "Falkland Islands (Malvinas)": 3,
   "Faroe Islands": 3,
   "Fiji": 5,
   "Finland": 3,
   "France": 5,
   "French Guiana": 4,
   "French Polynesia": 3,
   "French Southern Territories": 5,
   "Gabon": 10,
   "Gambia": 6,
   "Georgia": 3,
   "Ghana": 4,
   "Gibraltar": 5,
   "Greece": 8,
   "Greenland": 3,
   "Grenada": 3,
   "Guadeloupe": 4,
   "Guam": 2,
   "Guatemala": 5,
   "Guernsey": 2,
   "Guinea": 7,
   "Guinea-Bissau": 2,
   "Guyana": 4,
   "Haiti": 3,
   "Heard Island and McDonald Islands": 6,
   "Holy See (Vatican City State)": 7,
   "Honduras": 3,
   "Hong Kong": 1,
   "Hungary": 3,
   "Iceland": 6,
   "India": 4,
   "Indonesia": 3,
   "Iran": 5,
   "Iraq": 4,
   "Ireland": 6,
   "Isle of Man": 5,
   "Israel": 4,
   "Italy": 1,
   "Jamaica": 4,
   "Japan": 4,
   "Jersey": 5,
   "Jordan": 6,
   "Kazakhstan": 5,
   "Kenya": 2,
   "Kiribati": 7,
   "Korea": 8,
   "Kuwait": 6,
   "Kyrgyz Republic": 4,
   "Lao People's Democratic Republic": 5,
   "Latvia": 4,
   "Lebanon": 2,
   "Lesotho": 3,
   "Liberia": 3,
   "Libyan Arab Jamahiriya": 3,
   "Liechtenstein": 12,
   "Lithuania": 3,
   "Luxembourg": 9,
   "Macao": 5,
   "Macedonia": 3,
   "Madagascar": 1,
   "Malawi": 5,
   "Malaysia": 4,
   "Maldives": 4,
   "Mali": 3,
   "Malta": 3,
   "Marshall Islands": 3,
   "Martinique": 3,
   "Mauritania": 5,
   "Mauritius": 2,
   "Mayotte": 1,
   "Mexico": 3,
   "Micronesia": 4,
   "Moldova": 4,
   "Monaco": 2,
   "Mongolia": 7,
   "Montenegro": 7,
   "Montserrat": 8,
   "Morocco": 7,
   "Mozambique": 2,
   "Myanmar": 2,
   "Namibia": 1,
   "Nauru": 4,
   "Nepal": 6,
   "Netherlands": 5,
   "Netherlands Antilles": 3,
   "New Caledonia": 5,
   "New Zealand": 1,
   "Nicaragua": 7,
   "Niger": 4,
   "Nigeria": 9,
   "Niue": 4,
   "Norfolk Island": 1,
   "Northern Mariana Islands": 5,
   "Norway": 1,
   "Oman": 4,
   "Pakistan": 4,
   "Palau": 5,
   "Palestinian Territory": 1,
   "Panama": 7,
   "Papua New Guinea": 7,
   "Paraguay": 1,
   "Peru": 1,
   "Philippines": 3,
   "Pitcairn Islands": 1,
   "Poland": 1,
   "Portugal": 2,
   "Puerto Rico": 3,
   "Qatar": 5,
   "Reunion": 9,
   "Romania": 5,
   "Russian Federation": 3,
   "Rwanda": 7,
   "Saint Barthelemy": 5,
   "Saint Helena": 5,
   "Saint Kitts and Nevis": 5,
   "Saint Lucia": 4,
   "Saint Martin": 1,
   "Saint Pierre and Miquelon": 5,
   "Saint Vincent and the Grenadines": 2,
   "Samoa": 5,
   "San Marino": 7,
   "Sao Tome and Principe": 2,
   "Saudi Arabia": 2,
   "Senegal": 7,
   "Serbia": 3,
   "Seychelles": 2,
   "Sierra Leone": 4,
   "Singapore": 2,
   "Slovakia (Slovak Republic)": 3,
   "Slovenia": 4,
   "Solomon Islands": 5,
   "Somalia": 3,
   "South Africa": 5,
   "South Georgia and the South Sandwich Islands": 7,
   "Spain": 1,
   "Sri Lanka": 5,
   "Sudan": 5,
   "Suriname": 2,
   "Svalbard & Jan Mayen Islands": 3,
   "Swaziland": 5,
   "Sweden": 4,
   "Switzerland": 7,
   "Syrian Arab Republic": 3,
   "Taiwan": 3,
   "Tajikistan": 4,
   "Tanzania": 5,
   "Thailand": 5,
   "Timor-Leste": 2,
   "Togo": 6,
   "Tokelau": 4,
   "Tonga": 4,
   "Trinidad and Tobago": 5,
   "Tunisia": 3,
   "Turkey": 6,
   "Turkmenistan": 7,
   "Turks and Caicos Islands": 3,
   "Tuvalu": 4,
   "Uganda": 8,
   "Ukraine": 4,
   "United Arab Emirates": 7,
   "United States Minor Outlying Islands": 4,
   "United States Virgin Islands": 2,
   "United States of America": 5,
   "Uruguay": 2,
   "Uzbekistan": 3,
   "Vanuatu": 5,
   "Venezuela": 3,
   "Vietnam": 3,
   "Wallis and Futuna": 3,
   "Western Sahara": 4,
   "Yemen": 7,
   "Zambia": 1,
   "Zimbabwe": 5,
}
