"""Solution for the Summarize exercise."""
SOLUTION = {'Afghanistan': 4,
 'Aguirrebury': 1,
 'Aimeeville': 1,
 'Albania': 2,
 'Alexaside': 1,
 'Alexfort': 1,
 'Alextown': 1,
 'Algeria': 3,
 'American Samoa': 5,
 'Andorra': 2,
 'Andreburgh': 1,
 'Angola': 2,
 'Anguilla': 7,
 'Antarctica (the territory South of 60 deg S)': 3,
 'Anthonyville': 1,
 'Antigua and Barbuda': 7,
 'Argentina': 1,
 'Armenia': 4,
 'Armstrongtown': 1,
 'Aruba': 5,
 'Australia': 3,
 'Austria': 1,
 'Azerbaijan': 3,
 'Bahamas': 2,
 'Bahrain': 2,
 'Baileyside': 1,
 'Bangladesh': 7,
 'Barbados': 3,
 'Barbaraborough': 1,
 'Batesville': 1,
 'Belarus': 2,
 'Belgium': 3,
 'Belize': 3,
 'Bellchester': 1,
 'Benin': 2,
 'Berrymouth': 1,
 'Bethanystad': 1,
 'Bethside': 1,
 'Bhutan': 2,
 'Billytown': 1,
 'Blakechester': 1,
 'Bolivia': 5,
 'Bonnieport': 1,
 'Bosnia and Herzegovina': 1,
 'Bouvet Island (Bouvetoya)': 4,
 'Brazil': 3,
 'Breannaton': 1,
 'Brewerbury': 1,
 'Brianbury': 1,
 'British Indian Ocean Territory (Chagos Archipelago)': 2,
 'British Virgin Islands': 4,
 'Bruceville': 1,
 'Brunei Darussalam': 4,
 'Bulgaria': 2,
 'Burchchester': 1,
 'Burkina Faso': 5,
 'Burundi': 4,
 'Calebbury': 1,
 'Cambodia': 4,
 'Cameroon': 2,
 'Canada': 2,
 'Cape Verde': 5,
 'Carneyfurt': 1,
 'Cayman Islands': 6,
 'Central African Republic': 4,
 'Cervantesmouth': 1,
 'Chad': 6,
 'Chadborough': 1,
 'Chile': 5,
 'China': 5,
 'Christianbury': 1,
 'Christmas Island': 4,
 'Chungbury': 1,
 'Cocos (Keeling) Islands': 1,
 'Collinstown': 1,
 'Collinton': 1,
 'Colombia': 2,
 'Comoros': 4,
 'Congo': 2,
 'Conradport': 1,
 'Cook Islands': 4,
 'Corystad': 1,
 'Costa Rica': 1,
 "Cote d'Ivoire": 3,
 'Coxburgh': 1,
 'Cristianmouth': 1,
 'Cuba': 1,
 'Czech Republic': 2,
 'Dariusview': 1,
 'Darrellstad': 1,
 'Deanchester': 1,
 'Deniseburgh': 1,
 'Denmark': 1,
 'Dianamouth': 1,
 'Dicksonburgh': 1,
 'Djibouti': 2,
 'Dominica': 4,
 'Dominican Republic': 3,
 'Douglasland': 1,
 'Douglasstad': 1,
 'East Alberthaven': 1,
 'East Chloeshire': 1,
 'East Daniellestad': 1,
 'East Darin': 1,
 'East Douglasberg': 1,
 'East Emma': 1,
 'East Gailhaven': 1,
 'East Glenn': 1,
 'East Isabel': 1,
 'East Jeanne': 1,
 'East Jonathan': 1,
 'East Josephfurt': 1,
 'East Katelynmouth': 1,
 'East Kristenfort': 1,
 'East Krystalland': 1,
 'East Mary': 1,
 'East Monica': 1,
 'East Normanchester': 1,
 'East Wayne': 1,
 'Ecuador': 6,
 'Egypt': 3,
 'El Salvador': 2,
 'Elijahchester': 1,
 'Elizabethburgh': 1,
 'Equatorial Guinea': 3,
 'Ericaside': 1,
 'Erikamouth': 1,
 'Eritrea': 1,
 'Estonia': 1,
 'Ethanburgh': 1,
 'Ethiopia': 2,
 'Falkland Islands (Malvinas)': 3,
 'Faroe Islands': 2,
 'Fiji': 2,
 'Finland': 1,
 'Flemington': 1,
 'Fletcherborough': 1,
 'Fordton': 1,
 'France': 2,
 'Franciscochester': 1,
 'Francisside': 1,
 'Frederickfurt': 1,
 'French Guiana': 2,
 'French Southern Territories': 4,
 'Fryeville': 1,
 'Fullerbury': 1,
 'Gabon': 9,
 'Gambia': 4,
 'Georgemouth': 1,
 'Georgeton': 1,
 'Georgia': 1,
 'Ghana': 4,
 'Gibraltar': 4,
 'Ginaport': 1,
 'Glenmouth': 1,
 'Grantmouth': 1,
 'Greece': 4,
 'Greenland': 2,
 'Grenada': 3,
 'Guadeloupe': 1,
 'Guatemala': 4,
 'Guernsey': 2,
 'Guinea': 2,
 'Guinea-Bissau': 1,
 'Guyana': 4,
 'Haiti': 2,
 'Harryview': 1,
 'Hatfieldbury': 1,
 'Heard Island and McDonald Islands': 4,
 'Hollandshire': 1,
 'Holy See (Vatican City State)': 7,
 'Honduras': 3,
 'Howardville': 1,
 'Hungary': 2,
 'Huntville': 1,
 'Iceland': 4,
 'India': 3,
 'Indonesia': 3,
 'Iran': 4,
 'Iraq': 3,
 'Ireland': 5,
 'Isle of Man': 5,
 'Israel': 4,
 'Italy': 1,
 'Jackbury': 1,
 'Jacobsonchester': 1,
 'Jamaica': 3,
 'Janetchester': 1,
 'Japan': 3,
 'Jeffreybury': 1,
 'Jermainetown': 1,
 'Jerrychester': 1,
 'Jersey': 3,
 'Jimmouth': 1,
 'Johnmouth': 1,
 'Jordan': 4,
 'Juarezbury': 1,
 'Julianberg': 1,
 'Juliantown': 1,
 'Karatown': 1,
 'Kaufmanfurt': 1,
 'Kazakhstan': 4,
 'Kenya': 1,
 'Kiarachester': 1,
 'Kiddfort': 1,
 'Kimberlyberg': 1,
 'Kiribati': 5,
 'Korea': 4,
 'Krausefurt': 1,
 'Kristinefurt': 1,
 'Kuwait': 4,
 'Kyrgyz Republic': 4,
 'Lake Alechaven': 1,
 'Lake Alisonside': 1,
 'Lake Amanda': 1,
 'Lake Brooke': 1,
 'Lake Calvin': 1,
 'Lake Darrellshire': 1,
 'Lake Devonmouth': 1,
 'Lake Dillonfort': 1,
 'Lake Douglas': 1,
 'Lake Edwintown': 1,
 'Lake Emily': 1,
 'Lake Faithton': 1,
 'Lake Francisfurt': 1,
 'Lake Jaclyn': 1,
 'Lake Joyton': 1,
 'Lake Lindaton': 1,
 'Lake Lindseyberg': 1,
 'Lake Lonnieberg': 1,
 'Lake Mike': 1,
 'Lake Omar': 1,
 'Lake Rachael': 1,
 'Lake Sean': 1,
 'Lake Sydney': 1,
 'Lake Xaviertown': 1,
 "Lao People's Democratic Republic": 2,
 'Latoyabury': 1,
 'Latvia': 2,
 'Laurieport': 1,
 'Lebanon': 2,
 'Lesliefurt': 1,
 'Lesotho': 2,
 'Liberia': 2,
 'Libyan Arab Jamahiriya': 2,
 'Liechtenstein': 9,
 'Lithuania': 1,
 'Longton': 1,
 'Lorettaland': 1,
 'Lorrainefort': 1,
 'Lunaville': 1,
 'Luxembourg': 5,
 'Macao': 4,
 'Macedonia': 2,
 'Madagascar': 1,
 'Maddenmouth': 1,
 'Malawi': 3,
 'Malaysia': 2,
 'Malta': 3,
 'Mannport': 1,
 'Marcusburgh': 1,
 'Margaretfurt': 1,
 'Marshall Islands': 2,
 'Martinique': 3,
 'Mataport': 1,
 'Mauriceview': 1,
 'Mauritania': 4,
 'Mauritius': 2,
 'Mayton': 1,
 'Mcdanielhaven': 1,
 'Melendezland': 1,
 'Mexico': 2,
 'Meyerfurt': 1,
 'Mezaview': 1,
 'Michaelport': 1,
 'Micronesia': 4,
 'Miguelhaven': 1,
 'Miketown': 1,
 'Moldova': 4,
 'Monaco': 2,
 'Mongolia': 5,
 'Montenegro': 2,
 'Montoyaberg': 1,
 'Montserrat': 8,
 'Moralesport': 1,
 'Morocco': 2,
 'Mozambique': 1,
 'Myanmar': 1,
 'Natalieton': 1,
 'Nauru': 2,
 'Nepal': 5,
 'Netherlands': 5,
 'Netherlands Antilles': 1,
 'New Alexa': 1,
 'New Bradybury': 1,
 'New Bruce': 1,
 'New Caledonia': 3,
 'New Christianburgh': 1,
 'New Derrick': 1,
 'New Diane': 1,
 'New Edwin': 1,
 'New Erica': 1,
 'New Erikville': 1,
 'New Joanneberg': 1,
 'New Johnnychester': 1,
 'New Julia': 2,
 'New Kelliechester': 1,
 'New Lanceview': 1,
 'New Mathew': 1,
 'New Melodymouth': 1,
 'New Michellefort': 1,
 'New Miguel': 1,
 'New Patriciamouth': 1,
 'New Ryan': 1,
 'New Samantha': 1,
 'New Savannah': 1,
 'New Shelleyfort': 1,
 'New Soniatown': 1,
 'New Tara': 1,
 'New Terryton': 1,
 'New Vincentstad': 1,
 'New Yolanda': 1,
 'Nicaragua': 6,
 'Nicolasfurt': 1,
 'Niger': 3,
 'Nigeria': 3,
 'Niue': 3,
 'Norfolk Island': 1,
 'North Adriana': 1,
 'North Carly': 1,
 'North Chris': 1,
 'North Davechester': 1,
 'North Diamond': 1,
 'North Douglas': 1,
 'North Dylan': 1,
 'North Elaine': 1,
 'North Evelynmouth': 1,
 'North Francis': 1,
 'North Jacquelineville': 1,
 'North Kirk': 1,
 'North Kristinside': 1,
 'North Leon': 1,
 'North Lynntown': 1,
 'North Melvin': 1,
 'North Monica': 1,
 'North Pattystad': 1,
 'North Renee': 1,
 'North Ritachester': 1,
 'North Shannon': 1,
 'North Sheilaland': 1,
 'North Suzanneberg': 1,
 'North Theodore': 1,
 'North Tracieview': 1,
 'North Tyler': 1,
 'North Yvetteview': 1,
 'Northern Mariana Islands': 3,
 'Nortonfort': 1,
 'Nortonmouth': 1,
 'Norway': 1,
 'Odonnellberg': 1,
 'Olsontown': 1,
 'Oman': 1,
 'Orrfurt': 1,
 'Pakistan': 3,
 'Palau': 3,
 'Palmerport': 1,
 'Pambury': 1,
 'Panama': 3,
 'Papua New Guinea': 2,
 'Parksfurt': 1,
 'Perkinsbury': 1,
 'Perkinshaven': 1,
 'Peru': 1,
 'Philippines': 2,
 'Poland': 1,
 'Port Beth': 1,
 'Port Calebhaven': 1,
 'Port Cameronbury': 1,
 'Port Carlos': 1,
 'Port Carlside': 1,
 'Port Cassandrastad': 1,
 'Port Christiemouth': 1,
 'Port Cristianview': 1,
 'Port Ebonyhaven': 1,
 'Port Erin': 1,
 'Port Grace': 1,
 'Port Jermaine': 1,
 'Port Jodi': 1,
 'Port Judith': 1,
 'Port Katherineside': 1,
 'Port Larryshire': 1,
 'Port Marieland': 1,
 'Port Mercedesberg': 1,
 'Port Michaelafort': 1,
 'Port Roberto': 1,
 'Port Russellmouth': 1,
 'Port Sheenaborough': 1,
 'Port Sylviaton': 1,
 'Portugal': 2,
 'Prestonchester': 1,
 'Princechester': 1,
 'Puerto Rico': 1,
 'Qatar': 4,
 'Quinnfurt': 1,
 'Rachelview': 1,
 'Reunion': 6,
 'Reynoldsborough': 1,
 'Rickyside': 1,
 'Rileyburgh': 1,
 'Romania': 3,
 'Rosefort': 1,
 'Russian Federation': 2,
 'Rwanda': 6,
 'Saint Barthelemy': 5,
 'Saint Helena': 2,
 'Saint Kitts and Nevis': 2,
 'Saint Lucia': 1,
 'Saint Pierre and Miquelon': 3,
 'Saint Vincent and the Grenadines': 2,
 'Samoa': 4,
 'San Marino': 6,
 'Santosport': 1,
 'Sao Tome and Principe': 1,
 'Saudi Arabia': 2,
 'Selenaville': 1,
 'Senegal': 6,
 'Serbia': 2,
 'Shannonstad': 1,
 'Sharonside': 1,
 'Shortmouth': 1,
 'Sierra Leone': 2,
 'Simonside': 1,
 'Singapore': 1,
 'Skinnerland': 1,
 'Sloanstad': 1,
 'Slovakia (Slovak Republic)': 2,
 'Slovenia': 3,
 'Solomon Islands': 3,
 'Somalia': 2,
 'South Africa': 3,
 'South Alisha': 1,
 'South Andreachester': 1,
 'South Antoniochester': 1,
 'South Caseyside': 1,
 'South Charleneport': 1,
 'South Chelseyton': 1,
 'South Christina': 1,
 'South Craig': 1,
 'South Cristian': 1,
 'South Dustin': 1,
 'South Francisco': 1,
 'South Georgia and the South Sandwich Islands': 5,
 'South Gilbertmouth': 1,
 'South Karl': 1,
 'South Latoya': 1,
 'South Lynnton': 1,
 'South Marciafurt': 1,
 'South Miamouth': 1,
 'South Shane': 1,
 'South Stephen': 1,
 'South Tamarafort': 1,
 'South Tashatown': 1,
 'South Theresafort': 1,
 'South Toddchester': 1,
 'South Tom': 1,
 'South Tonya': 2,
 'Spain': 1,
 'Spencerchester': 1,
 'Sri Lanka': 3,
 'Staffordhaven': 1,
 'Stanleybury': 1,
 'Sudan': 3,
 'Suriname': 1,
 'Svalbard & Jan Mayen Islands': 2,
 'Swaziland': 3,
 'Sweden': 1,
 'Switzerland': 4,
 'Syrian Arab Republic': 1,
 'Taiwan': 3,
 'Tajikistan': 3,
 'Tammieborough': 1,
 'Tanyachester': 1,
 'Tanzania': 4,
 'Tatemouth': 1,
 'Thailand': 3,
 'Theresaland': 1,
 'Thomasstad': 1,
 'Togo': 3,
 'Tokelau': 3,
 'Tommyland': 1,
 'Tonga': 2,
 'Trinidad and Tobago': 3,
 'Tuckerfurt': 1,
 'Tunisia': 2,
 'Turkey': 5,
 'Turkmenistan': 5,
 'Turks and Caicos Islands': 3,
 'Tuvalu': 2,
 'Uganda': 5,
 'Ukraine': 3,
 'United Arab Emirates': 6,
 'United States Minor Outlying Islands': 4,
 'United States of America': 2,
 'Uruguay': 2,
 'Uzbekistan': 1,
 'Vanessabury': 1,
 'Vanuatu': 4,
 'Vegaview': 1,
 'Venezuela': 1,
 'Vickietown': 1,
 'Vickimouth': 1,
 'Vietnam': 2,
 'Wadeborough': 1,
 'Wallacestad': 1,
 'Wallaceville': 1,
 'Wallis and Futuna': 2,
 'Weberview': 1,
 'Welchburgh': 1,
 'West Ana': 1,
 'West Brandonfurt': 1,
 'West Bryan': 1,
 'West Cristian': 1,
 'West Dan': 1,
 'West Emma': 1,
 'West Henry': 1,
 'West Kathryn': 1,
 'West Kendra': 1,
 'West Melody': 1,
 'West Meredithshire': 1,
 'West Normaton': 1,
 'West Pamela': 1,
 'West Ralph': 1,
 'West Raven': 1,
 'West Sandra': 1,
 'West Sharonville': 1,
 'West Sophiafort': 1,
 'West Tammieport': 1,
 'West Tyrone': 1,
 'West Vanessahaven': 1,
 'Western Sahara': 3,
 'Whitneyburgh': 1,
 'Wigginsbury': 1,
 'Wilkinsonton': 1,
 'Wyattborough': 1,
 'Yemen': 6,
 'Yvetteville': 1,
 'Zambia': 1,
 'Zimbabwe': 4}